# Generated by Django 2.2.1 on 2019-05-16 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='nome do plano')),
                ('descricao', models.TextField(blank=True, max_length=100, verbose_name='descricao do plano')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='valor')),
                ('desconto_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='desconto maximo %')),
                ('observacoes', models.TextField(blank=True, max_length=250, verbose_name='observacoes')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(blank=True, max_length=50, unique=True, verbose_name='razao social')),
                ('nome_fantasia', models.CharField(max_length=50, unique=True, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=20, unique=True, verbose_name='cnpj')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, unique=True, verbose_name='inscricao estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, unique=True, verbose_name='inscricao municipal')),
                ('contato', models.CharField(max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('site', models.CharField(blank=True, max_length=50)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('endereco', models.CharField(blank=True, max_length=40)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=40)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('contato_cobranca', models.CharField(blank=True, max_length=50)),
                ('telefone_cobranca', models.CharField(blank=True, max_length=30)),
                ('celular_cobranca', models.CharField(blank=True, max_length=30)),
                ('email_cobranca', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('cep_cobranca', models.CharField(blank=True, max_length=9)),
                ('endereco_cobranca', models.CharField(blank=True, max_length=40)),
                ('numero_cobranca', models.CharField(blank=True, max_length=10)),
                ('complemento_cobranca', models.CharField(blank=True, max_length=40)),
                ('bairro_cobranca', models.CharField(blank=True, max_length=50)),
                ('cidade_cobranca', models.CharField(blank=True, max_length=50)),
                ('uf_cobranca', models.CharField(blank=True, max_length=2)),
                ('dia_pagamento', models.IntegerField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(choices=[('A VISTA', 'A VISTA'), ('PARCELADO', 'PARCELADO'), ('FREE', 'FREE')], max_length=20, verbose_name='forma pagamento')),
                ('meio_pagamento', models.CharField(choices=[('BOLETO BANCARIO', 'BOLETO BANCARIO'), ('DEPOSITO EM CONTA', 'DEPOSITO EM CONTA'), ('CARTAO DE CREDITO', 'CARTAO DE CREDITO'), ('CARTAO DE DEBITO', 'CARTAO DE DEBITO'), ('GRATUIDADE', 'GRATUIDADE'), ('OUTROS', 'OUTROS')], max_length=20, verbose_name='meio de pagamento')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('SUSPENSO', 'SUSPENSO'), ('EXCLUIDO', 'EXCLUIDO'), ('NEGATIVADO', 'NEGATIVADO')], max_length=20, verbose_name='status')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('contrato', models.CharField(blank=True, max_length=30, verbose_name='contrato')),
                ('observacoes', models.TextField(blank=True, max_length=250)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresas.Planos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empresas',
                'ordering': ('nome_fantasia',),
            },
        ),
        migrations.CreateModel(
            name='EmpresaResponsaveis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacoes', models.TextField(blank=True, max_length=250)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresas.Empresas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empresas_responsaveis',
                'ordering': ('empresa',),
            },
        ),
    ]
