# Generated by Django 2.2.1 on 2019-05-16 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('sobre_nome', models.CharField(max_length=30)),
                ('rg', models.CharField(blank=True, max_length=15)),
                ('cpf', models.CharField(blank=True, max_length=15)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'SOLTEIRO'), ('CASADO', 'CASADO'), ('VIUVO', 'VIUVO'), ('DIVORCIADO', 'DIVORCIADO'), ('SEPARADO', 'SEPARADO'), ('UNIAO ESTAVEL', 'UNIAO ESTAVEL')], max_length=15)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO')], max_length=15, verbose_name='Sexo')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='cep')),
                ('endereco', models.CharField(blank=True, max_length=50, verbose_name='endereco')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='numero')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=50, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=50, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, max_length=50, verbose_name='estado')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('EXCLUIDO', 'EXCLUIDO'), ('AFASTADO', 'AFASTADO'), ('APOSENTADO', 'APOSENTADO'), ('DESLIGADO', 'DESLIGADO')], max_length=15, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, max_length=200)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresas.Empresas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'colaboradores',
                'ordering': ('nome',),
            },
        ),
    ]
