# Generated by Django 2.2.1 on 2019-05-16 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_razao_social', models.CharField(blank=True, max_length=150, unique=True, verbose_name='razao social')),
                ('nome_fantasia', models.CharField(max_length=100, unique=True, verbose_name='nome fantasia')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, unique=True, verbose_name='cnpj')),
                ('rg_inscricao_estadual', models.CharField(blank=True, max_length=20, unique=True, verbose_name='inscricao estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, unique=True, verbose_name='inscricao municipal')),
                ('contato', models.CharField(max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('site', models.CharField(blank=True, max_length=50)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('endereco', models.CharField(blank=True, max_length=40)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=40)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('contato_cobranca', models.CharField(blank=True, max_length=50)),
                ('telefone_cobranca', models.CharField(blank=True, max_length=30)),
                ('celular_cobranca', models.CharField(blank=True, max_length=30)),
                ('email_cobranca', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('cep_cobranca', models.CharField(blank=True, max_length=9)),
                ('endereco_cobranca', models.CharField(blank=True, max_length=40)),
                ('numero_cobranca', models.CharField(blank=True, max_length=10)),
                ('complemento_cobranca', models.CharField(blank=True, max_length=40)),
                ('bairro_cobranca', models.CharField(blank=True, max_length=50)),
                ('cidade_cobranca', models.CharField(blank=True, max_length=50)),
                ('uf_cobranca', models.CharField(blank=True, max_length=2)),
                ('forma_pagamento', models.CharField(choices=[('A VISTA', 'A VISTA'), ('PARCELADO', 'PARCELADO')], max_length=20, verbose_name='forma pagamento')),
                ('meio_pagamento', models.CharField(choices=[('BOLETO BANCARIO', 'BOLETO BANCARIO'), ('DEPOSITO EM CONTA', 'DEPOSITO EM CONTA'), ('CARTAO DE CREDITO', 'CARTAO DE CREDITO'), ('CARTAO DE DEBITO', 'CARTAO DE DEBITO'), ('GRATUIDADE', 'GRATUIDADE'), ('OUTROS', 'OUTROS')], max_length=20, verbose_name='meio de pagamento')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('SUSPENSO', 'SUSPENSO'), ('EXCLUIDO', 'EXCLUIDO'), ('NEGATIVADO', 'NEGATIVADO')], max_length=20, verbose_name='status')),
                ('pessoa', models.CharField(choices=[('FISICA', 'FISICA'), ('JURIDICA', 'JURIDICA')], max_length=20, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, max_length=250)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresas.Empresas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fornecedores',
                'ordering': ('nome_fantasia',),
            },
        ),
    ]
