# Generated by Django 2.2.1 on 2019-05-16 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_simplificada', models.CharField(max_length=100, null=True)),
                ('unidade_medida', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=30)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default='0.0', max_digits=15)),
                ('estoque_maximo', models.DecimalField(decimal_places=3, default='0.0', max_digits=15)),
                ('estoque_atual', models.DecimalField(decimal_places=3, default='0.0', max_digits=15)),
                ('fracionar_produto', models.CharField(max_length=5)),
                ('id_embalagem_fechada', models.IntegerField(default='0')),
                ('quantidade_embalagem_fechada', models.DecimalField(decimal_places=3, default='0', max_digits=15)),
                ('valor_compra', models.DecimalField(decimal_places=3, default='0', max_digits=15)),
                ('percentual_lucro', models.DecimalField(decimal_places=3, default='0', max_digits=15)),
                ('desconto_maximo', models.DecimalField(decimal_places=3, default='0', max_digits=5)),
                ('atacado_apartir', models.DecimalField(decimal_places=3, default='0', max_digits=15)),
                ('atacado_desconto', models.DecimalField(decimal_places=3, default='0', max_digits=5)),
                ('status', models.CharField(default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, max_length=200)),
                ('marketing', models.CharField(blank=True, default='', max_length=500)),
                ('preco_venda', models.DecimalField(decimal_places=2, default='0', max_digits=15)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('marca', models.CharField(max_length=30)),
                ('imagem', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50)),
                ('anunciar_produto', models.IntegerField(default=0)),
                ('descricao_completa', models.CharField(blank=True, max_length=500, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
            ],
            options={
                'db_table': 'produtos',
                'ordering': ('descricao_simplificada',),
            },
        ),
        migrations.CreateModel(
            name='TabelaPrecos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('preco_venda', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('observacoes_preco', models.TextField(blank=True, max_length=200)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('status_preco', models.CharField(default='ATIVO', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produtos')),
            ],
            options={
                'db_table': 'tabela_precos',
                'ordering': ('produto',),
            },
        ),
        migrations.CreateModel(
            name='PrecosPomocionais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_desconto', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('preco_venda_promocao', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('inicio_promocao', models.DateField()),
                ('fim_promocao', models.DateField()),
                ('status_promocao', models.CharField(default='ATIVO', max_length=10)),
                ('observacoes_promocao', models.TextField(blank=True, max_length=200)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
                ('produto_promocao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produtos')),
            ],
            options={
                'db_table': 'precos_promocionais',
                'ordering': ('produto_promocao',),
            },
        ),
        migrations.CreateModel(
            name='ImagensProdutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.CharField(blank=True, max_length=50, null=True)),
                ('sequencia', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produtos')),
            ],
            options={
                'db_table': 'imagens_produtos',
                'ordering': ['sequencia'],
            },
        ),
    ]
